# Generated by Django 5.0.6 on 2024-05-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_hours_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='organizerName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='organizerPhone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='role',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='event',
            field=models.CharField(max_length=100),
        ),
    ]
