# Generated by Django 5.0.6 on 2024-05-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_hours_portfolio', '0002_entry_description_entry_organizername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='organizerName',
            new_name='organizer',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='organizerPhone',
        ),
    ]
