# Generated by Django 5.0.6 on 2024-05-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='school',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
