from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=200)
class Volunteer(models.Model):
    id = models.CharField(max_length=200, unique= True)
    name = models.CharField(max_length=60)
    email = models.CharField(max_length=60, unique= True)

class Event(models.Model):
    id = models.CharField(max_length=200, unique= True)
    STATUS = (
        ('OPEN','OPEN'), 
        ('CLOSED','CLOSED'),
        )
    LOCATION = (
        ('Los Angeles','Los Angeles')
        ('San Diego','San Diego')
        ('San Jose','San Jose')
        ('San Francisco','San Francisco')
        ('Fresno','Fresno')
        ('Sacramento','Sacramento')
        ('Long Beach','Long Beach')
        ('Oakland','Oakland')
        ('Bakersfield','Bakersfield')
        ('Anaheim','')
        ('Stockton','')
        ('Riverside','')
        ('Santa Ana','')
        ('Irvine','')
        ('Chula Vista','')
        ('Fremont','')
        ('Santa Clarita','')
        ('San Bernardino','')
        ('Modesto','')
        ('Moreno Valley','')
        ('Fontana','')
        ('Oxnard','')
        ('Huntington Beach','')
        ('Glendale','')
        ('Santa Rosa','')
        ('Ontario','')
        ('Elk Grove','')
        ('Rancho Cucamonga','')
        ('Oceanside','')
        ('Garden Grove','')
        ('Lancaster','')
        ('Palmdale','')
        ('Salinas','')
        ('Hayward','')
        ('Escondido','')
        ('Pomona','')
        ('Roseville','')
        ('Torrance','')
        ('Fullerton','')
        ('Visalia','')
        ('Orange','')
        ('Pasadena','')
        ('Santa Clara','')
        ('Thousand Oaks','')
        ('Simi Valley','')
        ('Vallejo','')
        ('Concord','')

        )
    name = models.CharField(max_length=60, unique=True)
    description = models.CharField(max_length=500, null=True)
    day = models.PositiveIntegerField(default=1,validators=[MinValueValidator(1), MaxValueValidator(31))
    month = models.PositiveIntegerField(default=1,validators=[MinValueValidator(1), MaxValueValidator(12)])
    volunteer_limit = models.PositiveIntegerField(default=1,validators=[MinValueValidator(1), MaxValueValidator(999)])
    current_volunteers = models.PositiveIntegerField(default=0,validators=[MinValueValidator(1), MaxValueValidator(999)])
    hours = models.PositiveIntegerField(default=0,max_length=3)
    date_posted = models.DateField(auto_now_add=True)
    status = models.CharField(choices=STATUS)
    location = models.CharField(choices=LOCATION)
    volunteers = models.ManyToManyField(Volunteer)
